# Project: Lesson05_StringProcessing
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o functions.o ../Hand-On-07/hand-on-07.o
LINKOBJ  = main.o functions.o ../Hand-On-07/hand-on-07.o
LIBS     = -L"D:/Programs/Code/Cpp/Dev_Cpp/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Programs/Code/Cpp/Dev_Cpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Programs/Code/Cpp/Dev_Cpp/Dev-Cpp/TDM-GCC-64/include" -I"D:/Programs/Code/Cpp/Dev_Cpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Programs/Code/Cpp/Dev_Cpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Programs/Code/Cpp/Dev_Cpp/Dev-Cpp/TDM-GCC-64/include" -I"D:/Programs/Code/Cpp/Dev_Cpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Programs/Code/Cpp/Dev_Cpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Programs/Code/Cpp/Dev_Cpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Lesson05_StringProcessing.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\Programs\Code\Cpp\Dev_Cpp\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

functions.o: functions.cpp
	$(CPP) -c functions.cpp -o functions.o $(CXXFLAGS)

../Hand-On-07/hand-on-07.o: ../Hand-On-07/hand-on-07.cpp
	$(CPP) -c ../Hand-On-07/hand-on-07.cpp -o ../Hand-On-07/hand-on-07.o $(CXXFLAGS)
